/**
 * AuraMap - Gemini API Integration Module
 * Handles client-side requests to the Google Gemini API to generate structured roadmaps.
 */

const GEMINI_API_BASE_URL = 'https://generativelanguage.googleapis.com/v1beta/models';

/**
 * Validates that the returned JSON object conforms to our required roadmap structure.
 * If something is missing, it will inject default placeholders to prevent UI crashes.
 */
function validateAndCleanRoadmap(data) {
    if (!data || typeof data !== 'object') {
        throw new Error('Invalid response received from AI. Not an object.');
    }

    const cleaned = {
        title: data.title || 'Custom Career Roadmap',
        description: data.description || 'A structured learning path generated by AuraMap.',
        difficulty: data.difficulty || 'Intermediate',
        estimatedWeeks: data.estimatedWeeks || 12,
        phases: Array.isArray(data.phases) ? data.phases : [],
        projects: Array.isArray(data.projects) ? data.projects : []
    };

    // Clean phases & topics
    cleaned.phases = cleaned.phases.map((phase, pIdx) => {
        const phaseId = phase.id || `p${pIdx + 1}`;
        const topics = Array.isArray(phase.topics) ? phase.topics : [];
        
        return {
            id: phaseId,
            title: phase.title || `Phase ${pIdx + 1}`,
            weeks: phase.weeks || `Weeks ${pIdx * 4 + 1}-${(pIdx + 1) * 4}`,
            description: phase.description || 'Core milestones for this phase.',
            topics: topics.map((topic, tIdx) => {
                const topicId = topic.id || `${phaseId}_t${tIdx + 1}`;
                return {
                    id: topicId,
                    title: topic.title || 'Core Topic',
                    description: topic.description || 'Explore the fundamentals and build standard workflows.',
                    hours: parseInt(topic.hours) || 10,
                    difficulty: topic.difficulty || 'Intermediate',
                    resources: Array.isArray(topic.resources) ? topic.resources.map(res => ({
                        name: res.name || 'Resource Tutorial',
                        link: res.link || 'https://google.com',
                        type: ['Course', 'Video', 'Article', 'Book'].includes(res.type) ? res.type : 'Article',
                        cost: ['Free', 'Paid'].includes(res.cost) ? res.cost : 'Free'
                    })) : [],
                    skills: Array.isArray(topic.skills) ? topic.skills : ['Fundamentals'],
                    tasks: Array.isArray(topic.tasks) ? topic.tasks : ['Explore documentation and practice coding templates.']
                };
            })
        };
    });

    // Clean projects
    cleaned.projects = cleaned.projects.map((proj, idx) => {
        return {
            title: proj.title || `Capstone Project ${idx + 1}`,
            level: proj.level || 'Intermediate',
            description: proj.description || 'Hands-on practical build task representing this milestone.',
            stack: Array.isArray(proj.stack) ? proj.stack : ['Python', 'JavaScript'],
            steps: Array.isArray(proj.steps) ? proj.steps : ['Setup base repository.', 'Implement core functionalities.', 'Deploy and share online.']
        };
    });

    return cleaned;
}

/**
 * Call Gemini API with user goal to generate a detailed roadmap JSON.
 */
async function generateAuraRoadmap(goal, apiKey, model = 'gemini-3.5-flash') {
    if (!apiKey) {
        throw new Error('API Key is missing. Please save your Gemini API Key in the settings dialog.');
    }

    const modelsToTry = [model];
    if (model === 'gemini-3.5-flash') {
        modelsToTry.push('gemini-2.5-flash');
    } else if (model === 'gemini-2.5-flash') {
        modelsToTry.push('gemini-3.5-flash');
    }

    const promptText = `
Generate a highly detailed, professional learning roadmap for a student whose goal is: "${goal}".
The roadmap should be broken down into progressive phases, ending with a couple of real-world capstone projects.

You MUST respond with a single, valid JSON object matching the following structure:
{
  "title": "e.g., Senior Machine Learning Engineer Path",
  "description": "e.g., A comprehensive path starting from data manipulation to neural network tuning and MLOps deployment.",
  "difficulty": "e.g., Advanced (or Beginner/Intermediate)",
  "estimatedWeeks": 24,
  "phases": [
    {
      "id": "phase1",
      "title": "e.g., Phase 1: Python and Mathematical Foundations",
      "weeks": "e.g., Weeks 1-6",
      "description": "e.g., Learn the core syntax, OOP in Python, and mathematical concepts of Linear Algebra and Statistics.",
      "topics": [
        {
          "id": "p1_t1",
          "title": "e.g., Scientific Python Stack (NumPy & Pandas)",
          "description": "e.g., Focus on vectorization, array slicing, data manipulation, cleaning datasets, and handling missing variables.",
          "hours": 15,
          "difficulty": "Beginner",
          "resources": [
            {
              "name": "e.g., Python Data Science Handbook",
              "link": "https://jakevdp.github.io/PythonDataScienceHandbook/",
              "type": "Book",
              "cost": "Free"
            },
            {
              "name": "e.g., Pandas Getting Started",
              "link": "https://pandas.pydata.org/docs/getting_started/index.html",
              "type": "Article",
              "cost": "Free"
            }
          ],
          "skills": ["Python", "NumPy Vectorization", "Pandas DataFrames", "Data Preprocessing"],
          "tasks": [
            "Write a script to load a 10MB CSV file and replace null values with the mean of the column.",
            "Create a 3D NumPy array and slice it along the third dimension."
          ]
        }
      ]
    }
  ],
  "projects": [
    {
      "title": "e.g., Housing Price Predictor Pipeline",
      "level": "Beginner",
      "description": "e.g., Perform full exploratory analysis, feature engineering, and train a regression model.",
      "stack": ["Python", "Scikit-Learn", "Matplotlib", "Pandas"],
      "steps": [
        "Load California housing dataset",
        "Perform correlation analysis and plot graphs",
        "Implement a Random Forest Regressor and tune hyperparameters",
        "Write unit tests for the transformation pipeline"
      ]
    }
  ]
}

Guidelines:
1. Provide actual, active URLs for learning resources where possible (e.g. standard documentation, free courses from platforms like Coursera/edX, Kaggle, freeCodeCamp, or official documentation links). Do not use fake or broken domains.
2. Under "type", you MUST choose one of: "Course", "Video", "Article", "Book".
3. Under "cost", you MUST choose one of: "Free", "Paid".
4. Ensure the total estimatedWeeks matches the sum of the weeks in the phases.
5. Create exactly 3 to 5 phases, with each phase having 2 to 4 distinct topics.
6. Provide exactly 2 or 3 high-quality hands-on projects suited to the path.
`;

    let lastError = null;

    for (const currentModel of modelsToTry) {
        const endpoint = `${GEMINI_API_BASE_URL}/${currentModel}:generateContent?key=${apiKey}`;
        const maxRetries = 2; // 3 attempts total per model

        for (let attempt = 0; attempt <= maxRetries; attempt++) {
            try {
                if (attempt > 0) {
                    console.log(`Retrying API call for model ${currentModel}. Attempt ${attempt}...`);
                    // Linear backoff delay: 1500ms, 3000ms
                    await new Promise(resolve => setTimeout(resolve, attempt * 1500));
                }

                const response = await fetch(endpoint, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        contents: [{
                            parts: [{ text: promptText }]
                        }],
                        generationConfig: {
                            responseMimeType: 'application/json',
                            temperature: 0.2
                        }
                    })
                });

                if (!response.ok) {
                    const errorDetails = await response.json().catch(() => ({}));
                    const apiMsg = errorDetails.error?.message || response.statusText;
                    
                    // If transient error (503/429) and we have attempts remaining, continue retry loop
                    if ((response.status === 503 || response.status === 429) && attempt < maxRetries) {
                        console.warn(`Transient API error (${response.status}): ${apiMsg}. Retrying...`);
                        continue;
                    }

                    throw new Error(`API Error (${response.status}): ${apiMsg}`);
                }

                const result = await response.json();
                let jsonText = '';
                
                if (result.candidates && result.candidates[0]?.content?.parts[0]?.text) {
                    jsonText = result.candidates[0].content.parts[0].text;
                } else {
                    throw new Error('Could not extract text content from the API response structure.');
                }

                const parsedData = JSON.parse(jsonText);
                return validateAndCleanRoadmap(parsedData);

            } catch (error) {
                console.error(`Error on model ${currentModel} (attempt ${attempt + 1}/${maxRetries + 1}):`, error);
                lastError = error;
                
                // If it was a network failure or JSON parse error, and we have retries left, retry.
                // Otherwise break out of the retry loop and try the next model.
                if (attempt >= maxRetries) {
                    break;
                }
            }
        }
    }

    throw lastError || new Error('Failed to generate roadmap after attempting retries and alternative model routing.');
}
